# -*- coding: utf-8 -*-
"""Cardio_trained_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxOcNjMXbzG1cxehzGxDCwfAmr2gbkVK
"""

# from google.colab import files
# uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('cardio_train.csv', sep=';')


print(df)
print(df.info())

df['age_years'] = (df['age'] / 365).round().astype(int)
df = df.drop(['id'], axis=1)
print(df)

# Display the new columns to confirm the changes
print("\nColumns after pre-processing:")
print(df.columns)

# Distribution of the target variable 'cardio'
plt.figure(figsize=(10,6))
sns.countplot(x='cardio', data=df)
plt.title('Distribution of Cardiovascular Disease (0: No, 1: Yes)')
plt.show()

# Distribution of Age
plt.figure(figsize=(10,6))
sns.histplot(df['age_years'], bins=20, kde=True)
plt.title('Age Distribution')
plt.xlabel('Age (Years)')
plt.show()

# Correlation between cholesterol and cardiovascular disease
plt.figure(figsize=(8, 5))
sns.barplot(x='cholesterol', y='cardio', data=df)
plt.title('Cardiovascular Disease by Cholesterol Level')
plt.show()

# Blood Pressure Distribution
df[['ap_hi', 'ap_lo']].hist(bins=15, figsize=(10, 5))
plt.suptitle('Blood Pressure Distribution (ap_hi and ap_lo)')
plt.show

df.rename(columns={'ap_hi': 'systolic', 'ap_low': 'diastolic'}, inplace=True)

import matplotlib.pyplot as plt

# Basic info
print("Shape:", df.shape)
print(df.describe().transpose())

# Age distribution
plt.figure(figsize=(8, 5))
plt.hist(df.get('age_years', []), bins=25)
plt.title("Age distribution (years)")
plt.xlabel("Age (years)")
plt.ylabel("Count")
plt.show()

# Target column
target = df.columns[-1]
target = 'cardio' if 'cardio' in df.columns else target
print("Target column used:", target)
print(df[target].value_counts())

# Target distribution plot
plt.figure(figsize=(4, 3))
vals = df[target].value_counts().sort_index()
plt.bar(vals.index.astype(str), vals.values)
plt.title("Target distribution")
plt.show()

# Calculate the correlation matrix
corr_matrix = df.corr()

# Plot the heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=.5)
plt.title('Correlation Matrix of Features')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define features (X) and target (y)
X = df.drop('cardio', axis=1)
y = df['cardio']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize models
models = {
    'Logistic Regression': LogisticRegression(solver='liblinear', random_state=42),
    'K-Nearest Neighbor (KNN)': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Support Vector Machine (SVM)': SVC(random_state=42)
}

# Train and evaluate models
accuracy_scores = {}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    accuracy_scores[name] = accuracy
    print(f"{name} Accuracy: {accuracy:.4f}")

# Find the best model
best_model_name = max(accuracy_scores, key=accuracy_scores.get)
print(f"\nBest performing model: {best_model_name} with an accuracy of {accuracy_scores[best_model_name]:.4f}")

# Example 1: a healthy person
example1_data = pd.DataFrame([
    [X_train['age'].mean(), # age
     1,   # gender (2)
     168, # height
     62,  # weight
     110, # ap_hi
     80,  # ap_lo
     1,   # cholesterol
     1,   # gluc
     0,   # smoke
     0,   # alco
     1,   # active
     50]   # age_years
], columns=X_train.columns) # Use the column names from X_train

# Example 2: a person with potential risk factors
example2_data = pd.DataFrame([
    [X_train['age'].mean(), # age
     2,   # gender (2)
     175, # height
     95,  # weight
     150, # ap_hi
     100, # ap_lo
     3,   # cholesterol
     1,   # gluc
     0,   # smoke
     0,   # alco
     1,   # active
     60]   # age_years
], columns=X_train.columns) # Use the column names from X_train

# Scale the new data using the same scaler
example1_scaled = scaler.transform(example1_data)
example2_scaled = scaler.transform(example2_data)

print("\n--- Predictions ---")
for name, model in models.items():
    pred1 = model.predict(example1_scaled)
    pred2 = model.predict(example2_scaled)

    # Change the output to "High Risk" or "Low Risk"
    print(f"\n{name} (Accuracy: {accuracy_scores[name]:.4f})")
    print(f"  Example 1 Prediction: {'High Risk' if pred1[0] == 1 else 'Low Risk'}")
    print(f"  Example 2 Prediction: {'High Risk' if pred2[0] == 1 else 'Low Risk'}")

